### ISSUE TITLE
Añadir número de semanas al calendario

### ISSUE THREAD

**Issue by Feer93** [GPSGroupC/frontend#14]
Añadir el número de semana a la que corresponde cada semana del calendario.

**Comment by Feer93** [comment]
Buenas Diego en el commit 6a13448fcf4b1eb8930806a31789128fe20ed380 he hecho que las semanas no se contaran dos veces, ya que cuando una semana empezaba en un nuevo mes la contaba como otra semana diferente:

Adjunto foto de a que me refiero:

![image](https://user-images.githubusercontent.com/33655360/147278062-b87efc73-6222-434e-b785-31932ed79d39.png)

La semana 12 empieza el 29 de Noviembre y termina el 5 de Diciembre, por lo que es una misma semana. No obstante, como añadimos una nueva línea en la tabla cuando acaba el mes, se contaba como una semana el 29 y 30 y del 31 al 5 como otra. El commit que menciono básicamente hace que cuente como una semana. También en el calendario de la EINA solo numeran hasta la semana 15 y Septiembre no lo numeran, no sé si tiene que ser igual o eso, yo en mi opinión Septiembre (2 convocatoria) no lo numeraría porque no tiene gran relevancia.

**Comment by dmarcob** [comment]
De acuerdo, nos quedan estos cambios pues:
- No  numerar las semanas de Septiembre.
- Numerar la primera semana de cada periodo aunque no empiece en Lunes
